# Site settings
title: uthline
email: uthline@uthline.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.uthline.net" # the base hostname & protocol for your site

twitter_username:
github_username: uthline

# Build settings
markdown: kramdown
